version: "3.9"
services:
  api:
    build: ./api
    ports:
      - "5000:80"
    networks:
      default:
        aliases:
          - py-demo-api
  ui:
    build: ./ui-next
    ports:
      - "3000:3000"
    depends_on:
      - api
