version: "3.9"
services:
  api:
    build: ./api
    ports:
      - "5000:80"
  # ui-python:
  #   build: ./ui-python
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - api
  ui-next:
    build: ./ui-next
    ports:
      - "3000:3000"
    depends_on:
      - api